---
abstract: 'Simple URI Encoding/Decoding'
author:
  - 'Mithun Ayachit <mithun@cpan.org>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-Encode
provides:
  URI::Encode:
    file: lib/URI/Encode.pm
    version: 0.02
requires:
  Encode: 2.12
  Test::More: 0
  version: 0
resources:
  homepage: http://search.cpan.org/dist/URI-Encode/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mithun/perl-uri-encode
version: 0.02
