---
abstract: 'Simple URI Encoding/Decoding'
author:
  - 'Mithun Ayachit <mithun@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-Encode
provides:
  URI::Encode:
    file: lib/URI/Encode.pm
    version: 0.04
requires:
  Encode: 2.12
  Test::More: 0
  perl: v5.8.1
  version: 0
resources:
  homepage: https://metacpan.org/module/URI::Encode
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mithun/perl-uri-encode
version: 0.04
