---
abstract: 'Simple percent Encoding/Decoding'
author:
  - 'Mithun Ayachit <mithun@cpan.org>'
build_requires:
  Test::More: 0
  version: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-Encode
provides:
  URI::Encode:
    file: lib/URI/Encode.pm
    version: 0.06
requires:
  Encode: 2.12
  perl: v5.8.1
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=URI-Encode
  homepage: https://github.com/mithun/perl-uri-encode
  license: http://dev.perl.org/licenses/
  repository: git://github.com/mithun/perl-uri-encode.git
version: 0.06
