---
name: URI-Encode
version: 0.01
author:
  - 'Mithun Ayachit <mithun@cpan.org>'
abstract: Simple URI Encoding/Decoding
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Encode: 2.12
  Test::More: 0
  version: 0
configure_requires:
  Module::Build: 0.35
provides:
  URI::Encode:
    file: lib/URI/Encode.pm
    version: 0.01
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
